import type { SidebarsConfig } from '@docusaus/plugin-content-docs';
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
/**
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

 * Soroban Cookbook Sidebar Configuration
 * Creating a structured learning path for Soroban development
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/setup',
        'getting-started/setup-linux',
        'getting-started/setup-windows',
        'getting-started/setup-macos',
        'getting-started/development-tools',
        'getting-started/stellar-cli-migration',
        'getting-started/first-contract',
        'getting-started/building-and-compilation',
        'getting-started/browser-server-compilation',
        'getting-started/contract-testing',
        'getting-started/local-testing-and-simulation',
        'getting-started/local-testing',
        'getting-started/testing-errors',
        'getting-started/networks',
        'getting-started/deploy-testnet',
        'getting-started/deploy-mainnet',
        'getting-started/contract-interaction',
        'getting-started/invoke-host-function',
        'getting-started/js-sdk',
        'getting-started/api-security',
        'getting-started/wallets',
        'getting-started/debugging',
        'getting-started/api-security',
        'contributing',
        'contributing/add-tested-example',
        'contributing/soroban-test-snapshots',
        'contributing/analytics-events',
        'contributing/versioning-strategy',
      ],
    },
    {
      type: 'category',
      label: 'Migrations',
      items: [
        'migrations/index',
        'migrations/baseline-22-0',
        'migrations/template',
      ],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      items: [
        'concepts/introduction',
        'concepts/overview',
        'concepts/best-practices',
        'concepts/error-handling',
        'concepts/storage',
        'concepts/storage-ttl',
        'concepts/constructors',
        'concepts/authorization',
        'concepts/custom-accounts',
        'concepts/authorization-trees',
        'concepts/events',
        'concepts/time-and-scheduling',
        'concepts/gas-and-resources',
        'concepts/simulation-and-footprints',
        'concepts/cross-contract-invocation',
        'concepts/randomness',
        'concepts/token-standards',
        'concepts/stellar-asset-contract',
        'concepts/sep-41-token-standard',
        'concepts/rpc-and-horizon',
        'concepts/contract-ids',
        'concepts/testing-strategies',
        'concepts/token-standards',
      ],
    },
    {
      type: 'category',
      label: 'Patterns',
      items: [
        'patterns/overview',
        'patterns/examples-index',
        'patterns/hello-world',
        'patterns/basic-token',
        'patterns/token-wrapper',
        'patterns/token-snapshot',
        'patterns/balance-snapshot',
        'patterns/custom-types',
        'patterns/token-standards',
        'patterns/authorization',
        'patterns/address-authorization',
        'patterns/error-handling',
        'patterns/error-recovery',
        'patterns/cross-contract',
        'patterns/escrow-basic',
        'patterns/escrow-multiparty',
        'patterns/escrow-basic',
        'patterns/multi-token-vault',
        'patterns/batch-operations',
        'patterns/optimization-playbook',
        'patterns/lifecycle-upgrades',
        'patterns/proposal-lifecycle',
        'patterns/simple-dao',
        'patterns/reentrancy-guard',
        'patterns/pull-payment',
        'patterns/flash-loan',
        'patterns/staking',
        'patterns/streaming-payments',
        'patterns/timelock-vault',
        'patterns/contract-factory',
        'patterns/contract-registry',
        'patterns/soulbound-token',
        'patterns/oracle-consumer',
        'patterns/oracle-price-source',
        'patterns/token-vesting',
        'patterns/contract-registry',
        'patterns/multisig-wallet',
      ],
    },
    {
      type: 'category',
      label: 'Security',
      items: [
        'security/fundamentals',
        'security/governance',
        'security/defi-patterns',
        'security/token-audit',
        'security/upgrade-checklist',
      ],
    },
  ],
  internalSidebar: [
    {
      type: 'category',
      label: 'Design System',
      items: [
        'design-system/buttons',
        'design-system/typography',
        'design-system/badges-tags',
        'design-system/empty-states',
      ],
    },
    {
      type: 'category',
      label: 'Components',
      items: ['components/buttons', 'components/testimonials'],
    },
    {
      type: 'category',
      label: 'Responsive',
      items: ['responsive/breakpoints'],
    },
    {
      type: 'category',
      label: 'Security Audit',
      items: ['security/code-audit'],
    },
    {
      type: 'category',
      label: 'Planning',
      items: [
        'planning/ab-testing',
        'planning/code-playground',
        'planning/video-tutorial-getting-started',
        'planning/video-tutorial-first-contract',
      ],
    },
    {
      type: 'category',
      label: 'Legal',
      items: [
        'legal/privacy',
      ],
    },
  ],
  contributorSidebar: [
    {
      type: 'category',
      label: 'Contributor Guides',
      items: [
        'contributing',
        'contributing/add-tested-example',
        'contributing/analytics-events',
        'contributing/versioning-strategy',
        'contributing/accessibility-guide',
        'contributing/image-optimization',
        'contributing/internal-linking',
        'contributing/mobile-performance',
        'contributing/performance-budgets',
        'contributing/performance-impact',
        'contributing/offline-behavior',
      ],
    },
  ],
const sidebars SidebarsConfig = {
	tutorialSidebar: [
		{
		 type: 'category',
		 label: 'Getting Started',
		 items: [
			'getting-started/setup',
			'getting-started/setup-linux',
			'getting-started/setup-windows',
			'getting-started/setup-macos',
			'/getting-started/development-tools',
			'getting-started/first-contract',
			'/getting-started/building-and-compilation',
			'/getting-started/browser-server-compilation',
			'getting-started/contract-testing',
			'getting-started/local-testing-and-simulation',
			'getting-started/deploy-testnet',
			'/getting-started/deploy-mainnet',
			'getting-started/contract-interaction',
			'/getting-started/debugging',
			'contributing',
			'contributing/add-tested-example',
			'/contributing/analytics-events',
			'contributing/versioning-strategy',
		],
		},
		{
		 type: 'category',
		 label: 'Migrations',
		 items: [
			'migrations/index',
			'migrations/baseline-22-0',
			'migrations/template',
			'contributing/offline-behavior',
		],
		},
		{
		 type: 'category',
		 label: 'Core Concepts',
		 items: [
			'concepts/introduction',
			'concepts/overview',
			'concepts/best-practices',
			'concepts/error-handling',
			'concepts/storage',
			'concepts/authorization',
			'/concepts/events',
			'concepts/time-and-scheduling',
			'concepts/gas-and-resources',
			'concepts/cross-contract-invocation',
			'/concepts/randomness',
		],
		},
		{
		 type: 'category',
		 label: 'Patterns',
		 items: [
			'patterns/overview',
			'patterns/hello-world',
			'patterns/basic-token',
			'patterns/token-snapshot',
			'patterns/custom-types',
			'patterns/token-standards',
			'patterns/authorization',
			'patterns/error-handling',
			'patterns/error-recovery',
			'patterns/escrow-multiparty',
			'patterns/multi-token-vault',
			'patterns/optimization-playbook',
			'patterns/lifecycle-upgrades',
			'patterns/proposal-lifecycle',
			'patterns/reentrancy-guard',
			'patterns/pull-payment',
			'patterns/streaming-payments',
			'patterns/contract-registry',
			'patterns/htlc-swap',
		],
		},
		{
		 type: 'category',
		 label: 'Security',
		 items: ['security/fundamentals', 'security/governance', 'security/defi-patterns', 'security/upgrade-checklist'],
		},
		{
		 type: 'category',
		 label: 'Design System',
		 items: [
			'design-system/buttons',
			'design-system/typography',
			'/design-system/badges-tags',
			'/design-system/empty-states',
		],
		},
		{
		 type: 'category',
		 label: 'Components',
		 items: ['components/buttons', 'components/testimonials'],
		},
		{
		 type: 'category',
		 label: 'Responsive',
		 items: ['responsive/breakpoints'],
		},
		{
		 type: 'category',
		 label: 'Security Audit',
		 items: ['security/code-audit'],
		},
		{
		 type: 'category',
		 label: 'Planning',
		 items: [
			'planning/ab-testing',
			'/planning/code-playground',
			'planning/video-tutorial-getting-started',
			'/planning/video-tutorial-first-contract',
		],
		},
		{
		 type: 'category',
		 label: 'Legal',
		 items: [
			'legal/privacy',
		],
		},
	],
};

export default sidebars;
